table tbl_dim_supplier
	lineageTag: 85ded288-c1b1-4cc2-a614-fea79b30b74a

	column pk_dim_supplier
		dataType: int64
		isNullable: false
		formatString: 0
		sourceProviderType: int
		lineageTag: cb884307-3aa5-4881-a94e-aec206656541
		summarizeBy: none
		sourceColumn: pk_dim_supplier

		annotation SummarizationSetBy = Automatic

	column supplier_code
		dataType: string
		sourceProviderType: varchar(400)
		lineageTag: dfc4f8d9-05e1-48b6-a31c-3df4aef27b86
		summarizeBy: none
		sourceColumn: supplier_code

		annotation SummarizationSetBy = Automatic

	column supplier_name
		dataType: string
		sourceProviderType: varchar(400)
		lineageTag: ed1bf58a-b4b2-4160-8be3-7349d8ca6bb7
		summarizeBy: none
		sourceColumn: supplier_name

		annotation SummarizationSetBy = Automatic

	column dwh_create_dttm
		dataType: dateTime
		isNullable: false
		formatString: General Date
		sourceProviderType: datetime
		lineageTag: 504ffae8-7880-40fa-821c-c47f36f4fde4
		summarizeBy: none
		sourceColumn: dwh_create_dttm

		variation Variation
			isDefault
			relationship: 4454a163-e262-4e5a-bb57-634915eb617c
			defaultHierarchy: LocalDateTable_e5d9e52c-29e1-4b52-857b-a87aa593ec42.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

	column dwh_modif_dttm
		dataType: dateTime
		isNullable: false
		formatString: General Date
		sourceProviderType: datetime
		lineageTag: 6dbf609b-448d-4111-a8f2-d0c4ad03c2b4
		summarizeBy: none
		sourceColumn: dwh_modif_dttm

		variation Variation
			isDefault
			relationship: c8dfccda-0c35-4392-b5c0-5414bf44e689
			defaultHierarchy: LocalDateTable_ae320afe-0c36-4ef1-9343-ff20539ef59b.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

	column branch_code
		dataType: string
		sourceProviderType: varchar(20)
		lineageTag: c0b679f3-7fb0-4872-8c25-1bf0bf7f3dbe
		summarizeBy: none
		sourceColumn: branch_code

		annotation SummarizationSetBy = Automatic

	partition tbl_dim_supplier = m
		mode: import
		source =
				let
				    Source = Sql.Database("misdev.database.windows.net", "Analytics_demo_DWH"),
				    data_tbl_dim_supplier = Source{[Schema="data",Item="tbl_dim_supplier"]}[Data],
				    #"Removed Columns" = Table.RemoveColumns(data_tbl_dim_supplier,{"data_source", "display_supplier_name", "supplier_source_code"})
				in
				    #"Removed Columns"

	changedProperty = Name

